language: ruby
#node_js
#services: mongodb

matrix:
  fast_finish: true
  
cache:
  - apt
  - npm
  - bundler
  - vendor/bundle
  - npm_modules
  - /tmp
  
script:
  - apt-get update -qq -y
  - chmod u+x travis.sh
  - ./travis.sh


#after_success:
#  - sleep 5; curl 0.0.0.0:3000
