language: ruby
#node_js
#services: mongodb
env:
  global:
    - MODE_DEBUG=false 
  matrix:
      - RUN="mean"
      - RUN="test_err"
      - RUN=mean
      - RUN=ruby
      - RUN=mongo
      - RUN=apt
      - RUN=ssh
      - RUN=all
  
        
      
cache:
  - apt
  - npm
  - bundler
#  - vendor/bundle
#  - npm_modules
#  - /tmp
#  - /opt
  
script:
  - sudo apt-get -y update 1>/dev/null
  - chmod u+x travis.sh
  - ./travis.sh


#after_success:
#  - sleep 5; curl 0.0.0.0:3000
