language: c #cp creationix/nvm/.travis.yml language section 
#node_js
#services: mongodb
#global:
#    - MODE_DEBUG=false 
    
matrix:
  allow_failures:
      - env: RUN="test_err"
  fast_finish: true
  
env:
  - RUN=apt
  - RUN=ssh
  - RUN=ruby
  - RUN=mongo
  - RUN=mean
  - RUN=all
  - RUN=test_err

        
      
cache:
  - apt
#  - npm
#  - bundler
#  - vendor/bundle
#  - npm_modules
#  - /tmp
#  - /opt

  
script:
  - sudo apt-get -y update 1>/dev/null
  - chmod u+x travis.sh
  - ./travis.sh
  
after_success:
  - echo success

after_failure:
  - chmod u+x bashism.sh
  - ./bashism.sh

#after_success:
#  - sleep 5; curl 0.0.0.0:3000
